apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: dev
  name: deploy01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodejs
  template:
    metadata:
      labels:
        app: nodejs
    spec:
      containers:
      - name: mynodejs
        image: techwithnc/nodejs:1.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
